backend:
  name: github
  repo: tofuwonder/health-info-site # Path to your Github repository
  branch: master # Branch to update
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "diseases"
  - label: "Diseases"
  - folder: "content/diseases"
  - create: true
  - slug: "{{slug}}"
  - fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}
